apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      namespace: dev
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.0-bookworm-otel
          imagePullPolicy: Always
          ports:
            - containerPort: 80
